// Generated by https://quicktype.io

export interface PageContent {
    __metadata: ResultMetadata;
    AttachmentFiles: AttachmentFiles;
    Title: string;
    Description: null;
    Button: Button | null;
    OrderNo: number | null;
    Section: string;
    PageName: string;
    ExpireDate: null | string;
    Attachments: boolean;
    [key: string]: any;
}

export interface AttachmentFiles {
    results: Result[];
}

export interface Result {
    __metadata: ResultMetadata;
    FileName: string;
    ServerRelativeUrl: string;
}

export interface ResultMetadata {
    id: string;
    uri: string;
    type: string;
    etag?: string;
}

export interface Button {
    __metadata: ButtonMetadata;
    Description: string;
    Url: string;
}

export interface ButtonMetadata {
    type: string;
}
